# jdbc_config   datasource
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.10:3306/febs_security?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
# Hikari will use the above plus the following to setup connection pooling
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariPool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

mybatis:
  mapper-locations: classpath:mapper/*.xml  # Mapper所在的配置文件路径，进行扫描
#  config-location: classpath:mybatis/mybatis-config.xml  # mybaits-config文件
  type-aliases-package: top.crazybanana.model.entity  # pojo所在的包，与表一一对应
  configuration:
    mapUnderscoreToCamelCase: true

logging:
  level:
    root: WARN
    top:
      crazybanana:
        mapper: TRACE